# Generated by Django 2.2.14 on 2020-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('18', '18'), ('19', '19')], default=18, max_length=1, verbose_name='年齢'),
            preserve_default=False,
        ),
    ]
