# Generated by Django 2.2.14 on 2020-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200718_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('18', '18'), ('19', '19'), ('20', '20')], max_length=2, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', '女性'), ('2', '男性')], max_length=1, verbose_name='性別'),
        ),
    ]
