# Generated by Django 2.2.14 on 2020-07-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200718_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='from_age',
            new_name='age',
        ),
    ]
