# Generated by Django 2.2.14 on 2020-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200718_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='holidays',
            field=models.CharField(choices=[('こだわらない', 'こだわらない'), ('土日', '土日'), ('平日', '平日'), ('不定期', '不定期'), ('その他', 'その他')], default=1, max_length=10, verbose_name='休日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearly_income',
            field=models.CharField(choices=[('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('800', '800'), ('900', '900'), ('1000', '1000'), ('1500', '1500'), ('2000', '2000'), ('3000', '3000')], max_length=6, verbose_name='年収'),
        ),
    ]
