# Generated by Django 2.2.14 on 2020-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20200718_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='holidays',
            field=models.CharField(choices=[('土日', '土日'), ('平日', '平日'), ('不定期', '不定期'), ('その他', 'その他')], max_length=10, verbose_name='休日'),
        ),
    ]
