# Generated by Django 2.2.14 on 2020-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20200718_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('短大/専門学校/高専卒', '短大/専門学校/高専卒'), ('高校卒', '高校卒'), ('大学卒', '大学卒'), ('大学院卒', '大学院卒')], default=1, max_length=10, verbose_name='学歴'),
            preserve_default=False,
        ),
    ]
