# Generated by Django 2.2.14 on 2020-07-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_profile_living_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(choices=[('飲まない', '飲まない'), ('飲む', '飲む'), ('ときどき飲む', 'ときどき飲む')], default=1, max_length=10, verbose_name='お酒'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cigarette',
            field=models.CharField(choices=[('吸わない', '吸わない'), ('吸う', '吸う'), ('吸う（電子タバコ）', '吸う（電子タバコ）'), ('非喫煙者の前では吸わない', '非喫煙者の前では吸わない'), ('相手が嫌ならやめる', '相手が嫌ならやめる'), ('ときどき吸う', 'ときどき吸う')], default=1, max_length=10, verbose_name='たばこ'),
            preserve_default=False,
        ),
    ]
