# Generated by Django 2.2.14 on 2020-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20200718_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(choices=[('飲まない', '飲まない'), ('飲む', '飲む'), ('ときどき飲む', 'ときどき飲む')], max_length=20, verbose_name='お酒'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cigarette',
            field=models.CharField(choices=[('吸わない', '吸わない'), ('吸う', '吸う'), ('吸う（電子タバコ）', '吸う（電子タバコ）'), ('非喫煙者の前では吸わない', '非喫煙者の前では吸わない'), ('相手が嫌ならやめる', '相手が嫌ならやめる'), ('ときどき吸う', 'ときどき吸う')], max_length=20, verbose_name='たばこ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('短大/専門学校/高専卒', '短大/専門学校/高専卒'), ('高校卒', '高校卒'), ('大学卒', '大学卒'), ('大学院卒', '大学院卒')], max_length=20, verbose_name='学歴'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='holidays',
            field=models.CharField(choices=[('土日', '土日'), ('平日', '平日'), ('不定期', '不定期'), ('その他', 'その他')], max_length=20, verbose_name='休日'),
        ),
    ]
