# Generated by Django 2.2.14 on 2020-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200718_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=10, verbose_name='性別'),
        ),
    ]
